Repository boostcampaitech5/level3_recsys_finalproject-recsys-03, pull requests merged in 2023-08, with the labels that each got.

#127 IMR-153 feat: change Spotify query language to Korean
  back/src/infer/spotify.py
Labels: enhancement

#128 IMR-154 docs: add preview video embed
  README.md
Labels: documentation

#129 IMR-155 feat : mongodb 연동 코드 추가
  back/.env-sample
  back/main.py
  back/requirements.txt
  back/src/api/feedback.py
  back/src/api/music.py
  back/src/db/__init__.py
  back/src/db/document/__init__.py
  back/src/db/document/artist.py
  back/src/db/document/inference.py
  back/src/db/document/playlist.py
  back/src/db/document/song.py
  back/src/db/document/user.py
  back/src/db/exception/__init__.py
  back/src/db/exception/artist.py
  back/src/db/exception/inference.py
  back/src/db/exception/playlist.py
  back/src/db/exception/song.py
  back/src/db/exception/user.py
  back/src/db/repository/__init__.py
  back/src/db/repository/artist.py
  back/src/db/repository/common.py
  back/src/db/repository/inference.py
  back/src/db/repository/playlist.py
  back/src/db/repository/song.py
  back/src/db/repository/user.py
  back/src/dto/model/__init__.py
  back/src/dto/model/artist.py
  back/src/dto/model/inference.py
  back/src/dto/model/playlist.py
  back/src/dto/model/song.py
  back/src/dto/model/user.py
  back/src/dto/request/__init__.py
  back/src/dto/request/feedback.py
  back/src/dto/request/music.py
  back/src/dto/response/__init__.py
  back/src/dto/response/music.py
  back/src/services/feedback.py
  back/src/services/music.py
  back/tests/__init__.py
  back/tests/db/__init__.py
  back/tests/db/repository/__init__.py
  back/tests/db/repository/common.py
  back/tests/db/repository/test_artist.py
  back/tests/db/repository/test_playlist.py
  back/tests/db/repository/test_song.py
  back/tests/db/repository/test_user.py
Labels: enhancement

#131 IMR-162 refactor : 백엔드 설정파일 리팩토링
  back/main.py
  back/src/config.py
  back/src/infer/spotify.py
Labels: enhancement, refactor

#132 IMR-159 feat : 사용자 인증 기능 추가
  back/requirements.txt
  back/src/api/__init__.py
  back/src/api/auth.py
  back/src/config.py
  back/src/db/document/__init__.py
  back/src/db/document/auth.py
  back/src/db/document/mixin/date.py
  back/src/db/exception/__init__.py
  back/src/db/exception/auth.py
  back/src/db/repository/__init__.py
  back/src/db/repository/auth.py
  back/src/db/repository/common.py
  back/src/dto/auth/__init__.py
  back/src/dto/auth/acesss_payload.py
  back/src/dto/auth/refresh_payload.py
  back/src/dto/model/__init__.py
  back/src/dto/model/auth.py
  back/src/dto/request/__init__.py
  back/src/dto/request/auth.py
  back/src/dto/response/__init__.py
  back/src/dto/response/auth.py
  back/src/exception_handler/__init__.py
  back/src/exceptions/__init__.py
  back/src/exceptions/auth.py
  back/src/exceptions/common.py
  back/src/exceptions/error_type.py
  back/src/services/auth.py
  back/src/services/jwt.py
  back/tests/db/repository/test_auth.py
Labels: enhancement

#133 IMR-165 fix : UpdatedAtMixin pre_save안먹히는 오류 수정
  back/src/db/document/auth.py
  back/src/db/document/mixin/date.py
Labels: bug

#134 IMR-168 test : AuthService 테스트 코드 작성
  back/tests/service/__init__.py
  back/tests/service/test_auth.py
Labels: test

#137 IMR-174 feat: MusicService에서 db를 사용
  back/README.md
  back/main.py
  back/src/api/music.py
  back/src/infer/preprocess.py
  back/src/infer/song.py
  back/src/infer/spotify.py
  back/src/services/music.py
  back/tests/service/test_music.py
Labels: enhancement

#139 IMR-176 refactor: 테스트 코드의 한글 함수 이름을 영문으로 수정
  back/tests/service/test_auth.py
  back/tests/service/test_music.py
Labels: refactor

#140 IMR-177 chore: 프론트 개발 서버 배포 자동화
  .github/workflows/deploy-front-dev-app.yaml
  front/.dockerignore
  front/Dockerfile.dev
  front/Dockerfile.prod
  front/README.md
Labels: chore

#141 IMR-177 chore: 프론트 개발 서버 배포 자동화 2트
  .github/workflows/deploy-front-dev-app.yaml
Labels: chore

#146 IMR-181 docs: change service architecture image
  docs/imgs/architecture_service.png
Labels: documentation
